[package]
name = "dif"
version = "2.0.0"
edition = "2024"
license = "MIT"

[features]
macros = ["dif_macros"]
async = ["dif_core/async"]
globals = ["dif_core/globals"]

[dependencies]
dif_core = { path = "dif_core" }
dif_macros = { path = "dif_macros", optional = true }

[dev-dependencies]
criterion = "0.8.2"
generic-tests = "0.1.3"

[[bench]]
name = "dif_bench"
path = "benches/dif_bench.rs"
harness = false

[workspace]
resolver = "3"
members = ["dif_core"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]